In [182]:
import pandas as pd
import numpy as np
import re

### Prices-Stock

In [183]:
df_ps = pd.read_csv('PRICES-STOCK.csv', sep='|')

In [184]:
df_ps.head()

      SKU BRANCH  PRICE  STOCK
0  142308    HRO   45.6      3
1  223240   RHSM   15.3      5
2   49514   RHSM   56.7     -2
3  111807   RHSM   48.0     -4
4  223543     MS    8.7     -1

In [185]:
len(df_ps)

2296767

### Products

In [186]:
df = pd.read_csv('PRODUCTS.csv', sep='|', engine='python')

# Branches & Prices Stock

#### RHSM

In [187]:
branch_name = 'RHSM'
prices_stock_df = df_ps[(df_ps['BRANCH'] == branch_name) & (df_ps['STOCK'] > 0)]

In [188]:
len(prices_stock_df)

230184

In [189]:
prices_stock_df.head()

       SKU BRANCH  PRICE  STOCK
1   223240   RHSM   15.3      5
15   85778   RHSM   64.2      5
18  111612   RHSM   79.5      3
25   23522   RHSM   47.1      2
39  300896   RHSM   50.7      5

#### MM

In [190]:
branch_name = 'MM'
br_mm = df_ps[(df_ps['BRANCH'] == branch_name) & (df_ps['STOCK'] > 0)]

In [191]:
len(br_mm)

229818

In [192]:
br_mm.head()

       SKU BRANCH  PRICE  STOCK
22   58179     MM   23.7      5
32  109068     MM   42.9      3
36  238114     MM   52.2      3
45  220215     MM   53.7      5
55   25336     MM   26.4      4

#### Join the dataframes

In [193]:
frames = [br_rhsm, br_mm]
prices_frame = pd.concat(frames)

In [194]:
len(prices_frame)

460002

#### Quitamos duplicados

In [195]:
prices_frame.drop_duplicates(subset="SKU", keep = 'first', inplace = True)

In [196]:
#Numero total de precios_and_stock
len(prices_frame)

248640

In [197]:
prices_frame.head()

       SKU BRANCH  PRICE  STOCK
1   223240   RHSM   15.3      5
15   85778   RHSM   64.2      5
18  111612   RHSM   79.5      3
25   23522   RHSM   47.1      2
39  300896   RHSM   50.7      5

# Products

In [198]:
df.head()

,SKU,BUY_UNIT,DESCRIPTION_STATUS,ORGANIC_ITEM,KIRLAND_ITEM,FINELINE_NUMBER,BARCODES,NAME,DESCRIPTION,IMAGE_URL,CATEGORY,SUB_CATEGORY,SUB_SUB_CATEGORY,BRAND
0,52572,UN,B,NaN,False,713115,693177767936,CANASTOS,<p>CANASTO CONEJO F1 A 1UN</p>,https://locahost:8000/images/693177767936?heig...,APPAREL,MENS WEAR,MEN - T-SHIRTS,PUPPY DOG PALS
1,278100,NaN,R,NaN,True,345827,399,LIMÃ“N COLIMA KGÂ Â Â,<p>LIMÃ“N COLIMA KGÂ Â Â </p>,https://locahost:8000/images/399?height=500&wi...,ENTERTAINMENT,TOYS & HOBBIES,PELUCHES,ENTRECOT
2,27404,KG,B,NaN,True,134923,762230099043,CHICLES,<p>TRIDENT 6S SANDIA 9GR</p>,https://locahost:8000/images/762230099043?heig...,HARDLINES,AUTOMOTIVE,APARIENCIA AUTOMOVIL,SPURA
3,215143,UN,CD,Y,True,773663,7501199416236,JABON LIQUIDO PARA MANOS VITAMINA E,<p>JABON LIQUIDO PARA MANOS VITAMINA E 442 ML....,https://locahost:8000/images/7501199416236?hei...,HARDLINES,SEASONAL,SEASONAL - EASTER,CHAMYTO
4,85805,KG,CD,N,False,233313,8410113003119,VINO TINTO GRAN CORONAS TORRES 750,<p>VINO TINTO GRAN CORONAS TORRES 750 1 PZA</p>,https://locahost:8000/images/8410113003119?hei...,CONSUMABLES,HOUSEHOLD CHEMICALS,AIR FRESHENER-DEODORIZER,POOPSIE

In [199]:
#Full Category
df['FULL_CATEGORY'] = df['CATEGORY'].str.cat(df['SUB_CATEGORY'], sep='|').str.lower()

#Nombre de la tienda
df['STORE'] = "Richart's"

In [200]:
#Quitamos etiquetas HTML
df['DESCRIPTION'] = df.DESCRIPTION.apply(lambda x: re.sub('<[^<]+?>', '', x))

In [201]:
#Extraemos PACKAGE
df['PACKAGE'] = df['DESCRIPTION'].str.extract(r'(\d{1,4} ?[a-zA-Z]{1,3}.?$)')

In [202]:
#Revisamos que colunas tienen valores vacios
df.columns[df.isna().any()].tolist()

['BUY_UNIT',
 'DESCRIPTION_STATUS',
 'ORGANIC_ITEM',
 'NAME',
 'CATEGORY',
 'SUB_CATEGORY',
 'SUB_SUB_CATEGORY',
 'BRAND',
 'FULL_CATEGORY',
 'PACKAGE']

In [203]:
#Limpiamos cada columna deacuerdo al tipo de dato
df['BUY_UNIT'].fillna("None", inplace=True)

In [204]:
df['DESCRIPTION_STATUS'].fillna("N", inplace=True)

In [205]:
df['ORGANIC_ITEM'].fillna("Miss", inplace=True)

In [206]:
df['NAME'].fillna("Miss", inplace=True)

In [207]:
df['CATEGORY'].fillna("MISS", inplace=True)

In [208]:
df['SUB_CATEGORY'].fillna("MISS", inplace=True)

In [209]:
df['SUB_SUB_CATEGORY'].fillna("MISS", inplace=True)

In [210]:
df['BRAND'].fillna("MISS", inplace=True)

In [211]:
df['FULL_CATEGORY'].fillna("none", inplace=True)

In [212]:
df['PACKAGE'].fillna("none", inplace=True)

In [213]:
df.columns[df.isna().any()].tolist()

[]

In [220]:
len(df)

321542

In [215]:
df_final = prices_frame.merge(df, on="SKU", how="inner")

In [216]:
df_final.head(25)

,SKU,BRANCH,PRICE,STOCK,BUY_UNIT,DESCRIPTION_STATUS,ORGANIC_ITEM,KIRLAND_ITEM,FINELINE_NUMBER,BARCODES,NAME,DESCRIPTION,IMAGE_URL,CATEGORY,SUB_CATEGORY,SUB_SUB_CATEGORY,BRAND,FULL_CATEGORY,STORE,PACKAGE
0,223240,RHSM,15.3,5,UN,B,Miss,False,786651,7501035912854,CEPILLO DENTAL INFANTIL TARZAN,CEPILLO DENTAL INFANTIL TARZAN 0 PZA,https://locahost:8000/images/7501035912854?hei...,DELI MEAT & CHEESE,SERVICE DELI,COM PREPARADAS,STUDIO LINE,deli meat & cheese|service deli,Richart's,0 PZA
1,85778,RHSM,64.2,5,None,CD,Y,True,859191,8410030007788,VINO TINTO MARUQES DE PENAMONTE,VINO TINTO MARUQES DE PENAMONTE 750 ML.,https://locahost:8000/images/8410030007788?hei...,HARDLINES,DISPOSABLE AND BIRTHDAY PARTY SUPPLIES,SUMINISTRO FIESTAS,MICROLAB,hardlines|disposable and birthday party supplies,Richart's,750 ML.
2,111612,RHSM,79.5,3,KG,R,Y,False,377418,33383653006,CORAZON DE APIO,CORAZON DE APIO 1 PZA,https://locahost:8000/images/33383653006?heigh...,BAKERY,BAKERY,CAKES - IN STORE,KARCHER,bakery|bakery,Richart's,1 PZA
3,23522,RHSM,47.1,2,KG,R,N,True,652595,780292000652,UNTABLE/FUNDIDO,Q CREMA UNT NAT 100 100GR,https://locahost:8000/images/780292000652?heig...,HOME,DOMESTIC GOODS,TOALLAS BAÃ‘O,H2O,home|domestic goods,Richart's,100GR
4,300896,RHSM,50.7,5,KG,A,Y,False,41651,81555966225,"POLVO L.A. GIRL STROBE LITE CA, 110 WATT","POLVO L.A. GIRL STROBE LITE CA, 110 WATT",https://locahost:8000/images/81555966225?heigh...,DELI MEAT & CHEESE,SERVICE DELI,CECINAS,BULL EYE,deli meat & cheese|service deli,Richart's,110 WATT
5,312333,RHSM,47.7,5,None,B,Miss,True,561086,6971165064944,"ANDADERA HOME LINE, AZUL MEDIO, UNITARIO","ANDADERA HOME LINE, AZUL MEDIO, UNITARIO",https://locahost:8000/images/6971165064944?hei...,MISS,MISS,MISS,SIEGEN,none,Richart's,none
6,243557,RHSM,40.8,5,None,N,Y,True,281828,7506110650447,LABIAL LIQUIDO,LABIAL LIQUIDO 3 GRS,https://locahost:8000/images/7506110650447?hei...,CONSUMABLES,HEALTH AND BEAUTY AIDS,CONDITIONER,DISNEY,consumables|health and beauty aids,Richart's,3 GRS
7,308283,RHSM,62.7,5,UN,R,Y,True,537892,7501253659968,GI LOPERAMIDA 2 MG 12 TAB,GI LOPERAMIDA 2 MG 12 TAB,https://locahost:8000/images/7501253659968?hei...,APPAREL,MENS WEAR,CABALLERO - DENIM,CUERVO,apparel|mens wear,Richart's,12 TAB
8,179071,RHSM,33.9,2,None,CD,N,True,149364,7501052411804,CAFE SOLUBLE CON AZUCAR,CAFE SOLUBLE CON AZUCAR 50 GRS,https://locahost:8000/images/7501052411804?hei...,HOME,HOUSEWARES,TABLEWARE,TATITO,home|housewares,Richart's,50 GRS
9,203424,RHSM,76.5,3,KG,N,Y,False,258186,7501085900023,LIMPIADOR MULTIUSOS,LIMPIADOR MULTIUSOS 490 ML.,https://locahost:8000/images/7501085900023?hei...,HOME,HOME FURNISHINGS,OFICINA,MEGAPLAST,home|home furnishings,Richart's,490 ML.
10,267633,RHSM,50.7,5,None,A,Y,False,692837,7501059932548,SENSE SARTEN 24CM,SENSE SARTEN 24CM 1 PZA,https://locahost:8000/images/7501059932548?hei...,HOME,FABRIC & CRAFTS,DECOR HOGAR - RELOJES,OZARK TRAIL,home|fabric & crafts,Richart's,1 PZA
11,63533,RHSM,12.6,5,UN,B,Y,True,532270,780465506093,DULCE,COLADO ORG CIRUELA 90GR,https://locahost:8000/images/780465506093?heig...,GROCERY,92 GROCERY,SOUPS - INSTANT-MIXES,PLAY-DOH,grocery|92 grocery,Richart's,90GR
12,188672,RHSM,49.2,1,None,A,Y,True,306208,8410707005017,BEBIDA SABOR PINA 100% FREE PRISMA JUVER,BEBIDA SABOR PINA 100% FREE PRISMA JUVER 1 LT.,https://locahost:8000/images/8410707005017?hei...,APPAREL,SLEEPWEAR,ROPA DORMIR HOMBRE,PIONERO,apparel|sleepwear,Richart's,1 LT.
13,68959,RHSM,28.5,4,None,CD,Y,True,772101,340068598000,KIWI TRADICIONAL,KIWI BOLSA 1 KILO 1UN,https://locahost:8000/images/340068598000?heig...,HOME,BEDDING,CAMA COLCHAS-PLUMONES,DINGO,home|bedding,Richart's,1UN
14,82080,RHSM,48.0,4,UN,CD,N,False,455337,3377271212027,VINO TINTO PAYS DOC ST. MARTIN D AUMES,VINO TINTO PAYS DOC ST. MARTIN D AUMES 750 ML.,https://locahost:8000/images/3377271212027?hei...,MISS,MISS,MISS,QUINTAY,none,Richart's,750 ML.
15,161896,RHSM,79.2,5,None,B,Miss,True,579108,7501204909937,PIMIENTA LIMÂ¿N FRASCO,PIMIENTA LIMÂ¿N FRASCO 80 GRS,https://locahost:8000/images/7501204909937?hei...,HOME,DOMESTIC GOODS,KITCHEN-DINING TEXTILES,PARTY EXPRESS,home|domestic goods,Richart's,80 GRS
16,124391,RHSM,19.2,4,UN,R,Miss,True,484397,70909034284,QUESO MOZARELLA,QUESO MOZARELLA 226 GRS,https://locahost:8000/images/70909034284?heigh...,HARDLINES,SPORTING GOODS,MALETAS Y BOLSOS,LOTO,hardlines|sporting goods,Richart's,226 GRS
17,56762,RHSM,16.2,1,KG,R,Miss,True,786916,40000704310,ESTUCHES,ESTUCHE TRINITY 1UN,https://locahost:8000/images/40000704310?heigh...,ENTERTAINMENT,ELECTRONICS,AUDIO - SUMINISTROS VIDEO,MIDEA,entertainment|electronics,Richart's,1UN
18,97873,RHSM,72.3,4,None,B,Y,False,804789,7501125182891,VOTRIPAX L 1 MG AMP 6 JGAS 3,VOTRIPAX L 1 MG AMP 6 JGAS 3 1 PZA,https://locahost:8000/images/7501125182891?hei...,HOME,HOUSEWARES,STORAGE -ORGANIZATION,AMBIENTES,home|housewares,Richart's,1 PZA
19,245032,RHSM,6.9,2,UN,R,Y,False,470127,7798095603765,LABIAL PRINCESAS,LABIAL PRINCESAS 34 GRS,https://locahost:8000/images/7798095603765?hei...,GROCERY,01 CANDY TOBACCO,CANDY - CHOCOLATE,PAHUILMO,grocery|01 candy tobacco,Richart's,34 GRS
20,136963,RHSM,50.1,5,KG,CD,N,False,335608,7503017070149,FLOR DE SAL VERDE CON APIO,FLOR DE SAL VERDE CON APIO 150 GRS,https://locahost:8000/images/7503017070149?hei...,HARDLINES,SEASONAL,SEASONAL - CHRISTMAS,SMILEYKIDS,hardlines|seasonal,Richart's,150 GRS
21,67002,RHSM,72.6,5,None,CD,Y,True,467755,66178707543,OTROS,DUO JABON Y CREMA 1UN,https://locahost:8000/images/66178707543?heigh...,APPAREL,MENS WEAR,MEN - T-SHIRTS,OMO,apparel|mens wear,Richart's,1UN
22,243679,RHSM,78.3,2,UN,B,Miss,True,911270,7501050631952,AFTER SUN SOLARCAINE ALOE BURN,AFTER SUN SOLARCAINE ALOE BURN 236 ML.,https://locahost:8000/images/7501050631952?hei...,ENTERTAINMENT,LARGE APPLIANCES,ELECTRODOMESTICOS - GRANDES,IRONADE,entertainment|large appliances,Richart's,236 ML.
23,305554,RHSM,24.9,1,KG,CD,Y,True,157184,7501032931582,AROMATIZANTE GLADE CONO GEL ODISEA AZUL,AROMATIZANTE GLADE CONO GEL ODISEA AZUL,https://locahost:8000/images/7501032931582?hei...,GROCERY,DAIRY PRODUCTS,YOGHURT,ROYAL GUARD,grocery|dairy products,Richart's,none
24,210366,RHSM,81.3,4,UN,A,Miss,False,371384,7502244767839,SHAMPOO 2 EN 1 MONSTER HIGH,SHAMPOO 2 EN 1 MONSTER HIGH 300 ML.,https://locahost:8000/images/7502244767839?hei...,ENTERTAINMENT,ELECTRONICS,MUSICAS,GENOVESE,entertainment|electronics,Richart's,300 ML.

In [126]:
#df_final.to_csv('dataframe_final.csv')

In [96]:
#df.to_csv('productos_PACK.csv')

In [217]:
f_frame = df_final[['SKU', 'BRANCH', 'PRICE', 'STOCK', 'STORE', 'BARCODES', 'BRAND', 'NAME', 'DESCRIPTION','PACKAGE','IMAGE_URL']].copy()

In [218]:
f_frame.head()

,SKU,BRANCH,PRICE,STOCK,STORE,BARCODES,BRAND,NAME,DESCRIPTION,PACKAGE,IMAGE_URL
0,223240,RHSM,15.3,5,Richart's,7501035912854,STUDIO LINE,CEPILLO DENTAL INFANTIL TARZAN,CEPILLO DENTAL INFANTIL TARZAN 0 PZA,0 PZA,https://locahost:8000/images/7501035912854?hei...
1,85778,RHSM,64.2,5,Richart's,8410030007788,MICROLAB,VINO TINTO MARUQES DE PENAMONTE,VINO TINTO MARUQES DE PENAMONTE 750 ML.,750 ML.,https://locahost:8000/images/8410030007788?hei...
2,111612,RHSM,79.5,3,Richart's,33383653006,KARCHER,CORAZON DE APIO,CORAZON DE APIO 1 PZA,1 PZA,https://locahost:8000/images/33383653006?heigh...
3,23522,RHSM,47.1,2,Richart's,780292000652,H2O,UNTABLE/FUNDIDO,Q CREMA UNT NAT 100 100GR,100GR,https://locahost:8000/images/780292000652?heig...
4,300896,RHSM,50.7,5,Richart's,81555966225,BULL EYE,"POLVO L.A. GIRL STROBE LITE CA, 110 WATT","POLVO L.A. GIRL STROBE LITE CA, 110 WATT",110 WATT,https://locahost:8000/images/81555966225?heigh...

In [219]:
f_frame.to_csv('PRODUCTOS_FINAL.csv')

### Consulta de SKU

In [145]:
price_product = 273572
precio = df_ps[(df_ps['SKU'] == price_product)]

In [146]:
precio

            SKU BRANCH  PRICE  STOCK
153294   273572     MS   55.5      2
350010   273572   RHSM    5.4     -3
617097   273572    HRO   12.3      2
1094913  273572   RHSM   37.5      1
1095957  273572     MS   59.7     -1
1768435  273572   RHSM    4.8      5
1825672  273572    NaN   46.5      1
2018111  273572    NaN   30.6     -4